# Generated by Django 4.0.1 on 2022-03-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('Принятый', 'Принятый'), ('Завершённый', 'Завершённый'), ('Отменённый', 'Отменённый')], default='Новый', max_length=20),
        ),
    ]
